package ec.edu.ups.est.practica.definitiva.vista.disco;

import ec.edu.ups.est.practica.definitiva.controlador.ControladorCantante;
import ec.edu.ups.est.practica.definitiva.modelo.Cantante;
import ec.edu.ups.est.practica.definitiva.modelo.Disco;
import javax.swing.JOptionPane;

public class EliminarDisco extends javax.swing.JInternalFrame {
    private Cantante cantanteTempo;
    private ControladorCantante controladorCantante;
    private Disco disco;
    /**
     * Creates new form BuscarDisco
     */
    public EliminarDisco(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
        bntBuscarDisco.setEnabled(false); // Se deshabilita el botón de búsqueda de disco al iniciar la ventana
        txtCodigo4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtIdCantante4 = new javax.swing.JTextField();
        bntBuscar4 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        txtNombre4 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtApellido4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtEdad4 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtNombreArtistico4 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtCodigo4 = new javax.swing.JTextField();
        txtNombreDisco4 = new javax.swing.JTextField();
        txtAnioLanzamiento4 = new javax.swing.JTextField();
        bntCancelar4 = new javax.swing.JButton();
        bntBuscarDisco = new javax.swing.JButton();
        btnEliminarCancion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Disco", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N

        jLabel37.setText("Buscar cantante para encontar disco : ");

        bntBuscar4.setText("Buscar");
        bntBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscar4ActionPerformed(evt);
            }
        });

        jLabel38.setText("NOBRE DEL DISCO");

        txtNombre4.setEditable(false);
        txtNombre4.setEnabled(false);
        txtNombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre4ActionPerformed(evt);
            }
        });

        jLabel39.setText("Nombre : ");

        jLabel40.setText("Apellido :");

        txtApellido4.setEditable(false);
        txtApellido4.setEnabled(false);

        jLabel41.setText("Edad :");

        txtEdad4.setEditable(false);
        txtEdad4.setEnabled(false);

        jLabel42.setText("Nombre artistico :");

        txtNombreArtistico4.setEditable(false);
        txtNombreArtistico4.setEnabled(false);

        jLabel43.setText("Codigo :");

        jLabel44.setText("Nombre :");

        jLabel45.setText("Año de lanzamiento :");

        txtCodigo4.setEnabled(false);
        txtCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo4ActionPerformed(evt);
            }
        });

        txtNombreDisco4.setEnabled(false);

        txtAnioLanzamiento4.setEnabled(false);
        txtAnioLanzamiento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioLanzamiento4ActionPerformed(evt);
            }
        });

        bntCancelar4.setText("Cancelar");
        bntCancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelar4ActionPerformed(evt);
            }
        });

        bntBuscarDisco.setText("Buscar");
        bntBuscarDisco.setEnabled(false);
        bntBuscarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarDiscoActionPerformed(evt);
            }
        });

        btnEliminarCancion.setText("Eliminar");
        btnEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCancionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCantante4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(101, 101, 101)
                                .addComponent(txtAnioLanzamiento4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntCancelar4))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombre4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel42))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreArtistico4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo4)
                            .addComponent(txtNombreDisco4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(btnEliminarCancion)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel38)
                                            .addComponent(bntBuscar4)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntBuscarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdCantante4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(txtApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtEdad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(txtNombreArtistico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bntBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscarDisco)
                    .addComponent(jLabel45)
                    .addComponent(txtAnioLanzamiento4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCancelar4))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtNombreDisco4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCancion)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscar4ActionPerformed
        if (txtIdCantante4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No está lleno el campo");
        } else {
            cantanteTempo = controladorCantante.buscarCantante(Integer.parseInt(txtIdCantante4.getText()));
            if (cantanteTempo != null) {
                txtNombre4.setText(cantanteTempo.getNombre());
                txtApellido4.setText(cantanteTempo.getApellido());
                txtEdad4.setText(String.valueOf(cantanteTempo.getEdad()));
                txtNombreArtistico4.setText(cantanteTempo.getNombreArtistico());
                bntBuscarDisco.setEnabled(true); // Habilita el botón de búsqueda de disco una vez que se encuentra el cantante
                txtCodigo4.setEnabled(true); // Habilita el campo de texto para ingresar el código del disco una vez que se encuentra el cantante
            } else {
                JOptionPane.showMessageDialog(this, "No existe " + txtIdCantante4.getText() + " en cantantes.");
            }
        }
    }//GEN-LAST:event_bntBuscar4ActionPerformed
    
    public void mostrarDatos(Cantante cantante){
        txtIdCantante4.setEnabled(false);
        bntBuscar4.setEnabled(false);
        txtNombre4.setText(cantante.getNombre());
        txtEdad4.setText( String.valueOf(cantante.getEdad()));
        txtNombreArtistico4.setText(cantante.getNombreArtistico());
        txtApellido4.setText(cantante.getApellido());
    }
    
    public void limpiarCampos(){
        txtIdCantante4.setText("");
        txtApellido4.setText("");
        txtCodigo4.setText("");
        txtEdad4.setText("");
        txtNombreArtistico4.setText("");
        txtNombreDisco4.setText("");
        txtAnioLanzamiento4.setText("");
        txtNombre4.setText("");
    }
    
    
    private void txtNombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre4ActionPerformed

    private void txtCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo4ActionPerformed

    private void txtAnioLanzamiento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioLanzamiento4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioLanzamiento4ActionPerformed

    private void bntCancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelar4ActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
        
        bntBuscar4.setEnabled(true);
        txtIdCantante4.setEnabled(true);
        bntBuscarDisco.setEnabled(false);
        txtCodigo4.setEnabled(false);
    }//GEN-LAST:event_bntCancelar4ActionPerformed

    private void bntBuscarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarDiscoActionPerformed
        if (txtCodigo4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No esta lleno el campo ");
        }else {
            disco = cantanteTempo.buscarDisco(Integer.parseInt(txtCodigo4.getText()));
            if (disco!=null) {
                
                txtAnioLanzamiento4.setText(String.valueOf(disco.getAnioDeLanzamiento()));
                txtNombreDisco4.setText(disco.getNombre());
            }else{
                txtAnioLanzamiento4.setText("");
                txtNombreDisco4.setText("");
                JOptionPane.showMessageDialog(this, "No se encuentra el disco el disco ");
            }
        }
    }//GEN-LAST:event_bntBuscarDiscoActionPerformed

    private void btnEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCancionActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas eliminar la cancion?");
        if (respuesta==JOptionPane.YES_OPTION) {
            controladorCantante.eliminarDisco(controladorCantante.buscarCantante(Integer.parseInt(txtIdCantante4.getText())),Integer.parseInt(txtCodigo4.getText()));
            JOptionPane.showMessageDialog(this, "El disco a sido eliminada con exito");
            this.limpiarCamposCancion();
            this.limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, "La cancion no a sido eliminada");
        }
    }//GEN-LAST:event_btnEliminarCancionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiarCampos();
        this.setVisible(false);
        
        bntBuscar4.setEnabled(true);
        txtIdCantante4.setEnabled(true);
        bntBuscarDisco.setEnabled(false);
        txtCodigo4.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
        private void limpiarCamposCancion(){
        txtCodigo4.setText("");
        txtNombre4.setText("");
        txtAnioLanzamiento4.setText("");
    }
    
    private boolean validacionDeCampos(){
        if (txtCodigo4.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar4;
    private javax.swing.JButton bntBuscarDisco;
    private javax.swing.JButton bntCancelar4;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarCancion;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtAnioLanzamiento4;
    private javax.swing.JTextField txtApellido4;
    private javax.swing.JTextField txtCodigo4;
    private javax.swing.JTextField txtEdad4;
    private javax.swing.JTextField txtIdCantante4;
    private javax.swing.JTextField txtNombre4;
    private javax.swing.JTextField txtNombreArtistico4;
    private javax.swing.JTextField txtNombreDisco4;
    // End of variables declaration//GEN-END:variables
}
